### ISSUE TITLE
amp-toolbox-optimizer return response non-latin character

### ISSUE THREAD

**Issue by mjuzefiszyn** [ampproject/amp-toolbox#1122]
Hello all, we wanted to share with you a problem about amp-toolbox-optimizer.

We have it implemented through AWS LAMBDA and we are finding that on certain occasions, randomly, it is generating non-latin (��) unicodes characters in the response.

For example here we [have saved a link](http://vader.news/.tests/ssr/errorencoding) with the reproduction of the problem.

It always happens randomly, it is not constant and over different content locations. We have ruled out that it is the origin by activating an internal monitoring that returns us in which process that character is found.
Any idea how to avoid this type of characters in the toolbox when delivering the response? Both when requesting the html to convert it or when delivering it we are using _'Content-Type': 'text / html; charset = utf-8'_

We hope you can help us. Thank you

**Comment by sebastianbenz** [comment]
Closing as not related to optimiser.
