### ISSUE TITLE
toolbox-optimizer: .cache directory in package

### ISSUE THREAD

**Issue by jleclanche** [ampproject/amp-toolbox#1131]
The following files are present in the @ampproject/toolbox-optimizer package:

```
./.cache/2ff5577010acefeceb6bfdeab769b276.json
./.cache/71aa06fe2328502246eaf0ba178b4d2c.json
./.cache/97dd8567b7e4775960c2064e20d6d08f.json
```

This may be intended, it may not be. I can't quite tell at first glance. But I thought it safer to just flag this.

**Comment by sebastianbenz** [comment]
Thanks for flagging! These files get created at installation time (to have optimiser functional, even if there's internet connectivity).

**Comment by jleclanche** [comment]
Gotcha, sorry for the noise!
