### ISSUE TITLE
Add support for script amp-onerror

### ISSUE THREAD

**Issue by honeybadgerdontcare** [ampproject/amp-toolbox#1146]
See https://github.com/ampproject/amphtml/issues/22543#issuecomment-673603872.

Support adding `<script amp-onerror>document.querySelector("script[src*='/v0.js']").onerror=function(){document.querySelector('style[amp-boilerplate]').textContent=''}</script>` to the `<head>` in AMP Optimizer.

**Comment by sebastianbenz** [comment]
Thanks! When will this be available in the validator?

**Comment by honeybadgerdontcare** [comment]
At the latest in two weeks. See cl/359398014.

**Comment by jridgewell** [comment]
We should probably wait for b/163852894 before adding it further.

**Comment by westonruter** [comment]
> We should probably wait for b/163852894 before adding it further.

Fixed on March 5th.

**Comment by schlessera** [comment]
I'm currently trying to implement this in the Node.JS and PHP versions of the Optimizer, but I'm having trouble producing the exact output the validator requires, as the DOM abstractions tend to introduce whitespace which is enough to invalidate the script.

**Comment by jridgewell** [comment]
Unfortunately, we cannot have whitespace here without the SHA hash being changed: https://elfin-saber-afternoon.glitch.me/

**Comment by schlessera** [comment]
I turns out it was not the DOM, but rather a beautify script that was running after the fact on the test files. This seems to be resolved for now: https://github.com/ampproject/amp-toolbox/pull/1195#issuecomment-816825900
