### ISSUE TITLE
Migrate to new postcss plugin API to avoid warning in console output

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp-toolbox#1150]
//cc @lluerich

**Comment by lluerich** [comment]
On it.

**Comment by lluerich** [comment]
1/2 occurrences fixes in #1153.

**Comment by sebastianbenz** [comment]
Could you maybe also migrate the other usage here:
https://github.com/ampproject/amp-toolbox/blob/main/packages/optimizer/lib/transformers/SeparateKeyframes.js#L102
?

>
