### ISSUE TITLE
Post CSS deprecated version in use for @ampproject/toolbox-optimizer

### ISSUE THREAD

**Issue by edoardofelici** [ampproject/amp-toolbox#1215]
Hi. I've noticed that when using version 2.7.6 of @ampproject/toolbox-optimizer, this message is issued for each HTML page that is passed through the optimizer: 

`postcss-amp-keyframes-mover: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration`

**Comment by sebastianbenz** [comment]
Thanks for letting us know! It's already fixed in main (you can use the latest canary).
