### ISSUE TITLE
Duplicated Tags from Optimizer

### ISSUE THREAD

**Issue by ezikialbasix** [ampproject/amp-toolbox#1238]
Hello, I'm attempting to use the optimizer, but I keep running into these issues.  The v0.mjs preload is duplicated.  One correct and one incorrect ( which throws a validation error ).  The other issue I'm having is, it keeps adding a duplicate boilerplate ( or runtime ) style tag.  This one throws a validation error because amp-custom isn't associated with it.. but it's not coming from my code.  

Am I configurating something incorrectly?  I don't have any options specified for the transformHtml.

![image](https://user-images.githubusercontent.com/15716702/121698367-eecbb000-ca9b-11eb-9e45-7abf2f567f16.png)
![image](https://user-images.githubusercontent.com/15716702/121698722-45d18500-ca9c-11eb-81ad-98460986d5b9.png)

**Comment by sebastianbenz** [comment]
Has this been resolved? What was the cause?

**Comment by ezikialbasix** [comment]
Ended up being a load balancer issue hitting my proxy twice.
