### ISSUE TITLE
amp-inputmask JS being added triggered by a SVG

### ISSUE THREAD

**Issue by bjalford** [ampproject/amp-toolbox#1245]
Not 100% sure but think the amp-inputmask JS is being auto added by the svg here:
<mask id="mask0" maskUnits="userSpaceOnUse" x="2" y="2" width="20" height="20">

resulting in: <script async nomodule src="https://cdn.ampproject.org/v0/amp-inputmask-0.1.js" crossorigin="anonymous" custom-element="amp-inputmask"></script>

Example: https://www.independent.co.uk/tv/editors-picks/greek-pilot-arrested-over-wife-s-death-hugs-victim-s-mother-v658d1e53?amp

**Comment by sebastianbenz** [comment]
Hey Brian! Can you share the svg? Or the untransformed version of the page?

**Comment by bjalford** [comment]
Here's the SVG. 

[svg-with-mask.txt](https://github.com/ampproject/amp-toolbox/files/6700734/svg-with-mask.txt)

**Comment by patrickkettner** [comment]
@sebastianbenz figured this out, but I don't know the best fix.

[this](https://github.com/ampproject/amp-toolbox/blob/6d589370a029ae520c2c6a6b52647d1b6805dfd9/packages/optimizer/lib/transformers/AutoExtensionImporter.js#L36) is being used [here](https://github.com/ampproject/amp-toolbox/blob/6d589370a029ae520c2c6a6b52647d1b6805dfd9/packages/optimizer/lib/transformers/AutoExtensionImporter.js#L104). 

In this context, [we are iterating over every tag](https://github.com/ampproject/amp-toolbox/blob/6d589370a029ae520c2c6a6b52647d1b6805dfd9/packages/optimizer/lib/transformers/AutoExtensionImporter.js#:~:text=rules.gettagsforformat) that is valid for an AMP document, which includes all SVG elements. As a result of the current manual mapping logic, all SVG elements that have a `mask` attribute (all of them?) end up being forced to match `amp-inputmask`. the main lib had a [similar issue](https://github.com/ampproject/amphtml/pull/29624) a bit ago.

I could brute force a "if (== inputmask)" type check here, but hacks of hacks on hacks :/
But the data structures munging going on are turning my brain to soup. The validator defines input as the only valid node type for inputmask, but I am not sure how to access that logic at this point in the code

**Comment by sebastianbenz** [comment]
Thanks for investigating Patrick! We got lucky here as there's actually a better way to detect amp-inputmask as the `mask` attribute is only allowed on the input element.
