### ISSUE TITLE
toolbox-optimizer doesn't work properly  

### ISSUE THREAD

**Issue by tsybulskyserg** [ampproject/amp-toolbox#1249]
I've created just a simple project for testing toolbox-optimizer

![image](https://user-images.githubusercontent.com/575944/123967987-80558000-d9bf-11eb-803a-cc778b8689a5.png)

But after the optimizer works the code is not valid(

![image](https://user-images.githubusercontent.com/575944/123968658-1a1d2d00-d9c0-11eb-9095-4fb7e3e3657d.png)

What am I doing wrong?

**Comment by sebastianbenz** [comment]
AMP Optimizer does not convert non-AMP tags to AMP tags (in your case the
`img` is breaking the validation).

>
