### ISSUE TITLE
AMP optimizer removing media queries

### ISSUE THREAD

**Issue by jessekinsman** [ampproject/amp-toolbox#1250]
We have noticed that media queries are stripped from our amp-images on amp optimized pages using the Node amp-optimizer.

However, the same exact page optimized on the google amp optimizer works fine with media queries intact. 

Here is an example of our amp-optimized page with media queries stripped from the images:
https://www.bedbathandbeyond.com/amp/wm-optimized/store/category/bath/13432/

<img width="395" alt="Screen Shot 2021-07-02 at 11 10 41 AM" src="https://user-images.githubusercontent.com/2584802/124313761-2ae7b300-db26-11eb-9b84-343900892ca1.png">

Google Cache optimized page
https://www.google.com/amp/s/www.bedbathandbeyond.com/amp/store/category/bath/13432/

<img width="393" alt="Screen Shot 2021-07-02 at 11 11 38 AM" src="https://user-images.githubusercontent.com/2584802/124313839-4d79cc00-db26-11eb-9663-415dd7ceb423.png">

Non-optimized amp page
https://www.bedbathandbeyond.com/amp/store/category/bath/13432/

Screenshot of the media queries intact on the google cached version
<img width="945" alt="Screen Shot 2021-07-02 at 11 14 37 AM" src="https://user-images.githubusercontent.com/2584802/124314100-b95c3480-db26-11eb-881c-04401309aa7f.png">

Screenshot of the media queries stripped from the images on the Node amp-optimizer version
<img width="839" alt="Screen Shot 2021-07-02 at 11 17 15 AM" src="https://user-images.githubusercontent.com/2584802/124314343-1821ae00-db27-11eb-9254-2ae9b0ce8d52.png">

Details:
Amp Version: Version 2106182132000
Amp toolbox optimize Version: v2.8.0
We are using [default](https://github.com/ampproject/amp-toolbox/tree/master/packages/optimizer#readme) settings
We are not defining a function for imageOptimizer

**Comment by sebastianbenz** [comment]
Is there a problem in how the page is rendered? Otherwise this works as intended. The media attribute requires the AMP Boilerplate to be present, which negatively impacts LCP, as it requires the AMP runtime to be downloaded perform the page can be rendered. AMP Optimizer removes the media attribute and replaces it with a pure CSS based implementation that works without boilerplate.

**Comment by sebastianbenz** [comment]
Sorry, missed the part that this caused the image to not be visible.

**Comment by sebastianbenz** [comment]
This has been fixed in release 2.8.3
