### ISSUE TITLE
AMP Optimizer failing when no script src present

### ISSUE THREAD

**Issue by ak1929** [ampproject/amp-toolbox#1253]
AMP optimizer keeps failing with `TypeError: Cannot read property 'match' of undefined` after updating to 2.8.2.

Not sure if this helps, but after logging a few things, this seems to be happening due to `node.attribs.src.match` in `findRuntimeScript` in HtmlDomHelper.js for script tags that don't have a source (eg: an `application/json` script for amp-access had `attribs: { id: 'amp-access', type: 'application/json' }`).

Can something be done to fix this from my end?

**Comment by sebastianbenz** [comment]
This has been fixed in release 2.8.3

**Comment by ak1929** [comment]
Thanks for the quick fix!
