### ISSUE TITLE
createFull/Fast modes

### ISSUE THREAD

**Issue by ofekrom** [ampproject/amp-toolbox#1257]
In the Amp Optimizer docs and in the main branch it seems these methods are already in place, but when installing package version 2.8.3 - it doesn't exist.

What am I missing?

Thanks!

**Comment by sebastianbenz** [comment]
These haven't been released yet, you can find the correct docs here: https://github.com/ampproject/amp-toolbox/tree/v2.8.3/packages/optimizer.
