### ISSUE TITLE
ERROR Install postcss

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amp-toolbox#1276]
```
ERROR Install postcss to move keyframe animations into amp-keyframes via `npm install postcss postcss-safe-parser cssnano-simple`
```

I got this error while trying to use @ampproject/toolbox-optimizer@3.0.0-canary.2

@sswissspidy ran into the same issue

cc @sebastianbenz in case he knows what the issue is

**Comment by swissspidy** [comment]
I believe #1277 fixes this, as it shouldn't warn about missing dependencies if the transformer was disabled in the first place.
