### ISSUE TITLE
Missing validation rules error when trying to auto import extensions in v2.8.6

### ISSUE THREAD

**Issue by SimonHogstromRonbol** [ampproject/amp-toolbox#1284]
When i run the AMP Optimizer 2.8.6 i get the following error:
AMP Optimizer AutoExtensionImporter ERROR Missing validation rules, cannot auto import extensions

when i downgrade to 2.8.4 i don't get the error.
is anyone else experiencing the same thing, or know how to fix it?

**Comment by SimonHogstromRonbol** [comment]
This is what my optimizer script looks like in my build process.

`const` AmpOptimizer = require('@ampproject/toolbox-optimizer');
const fs = require('fs');
const path = require('path');

const optimizer = AmpOptimizer.create({
    minify: true,
	optimizeHeroImages: false,
	preloadHeroImage: false
});
const filePath = "_app";
const basenames = [];

console.log("running totem script (amp-optimizer)");

var walk = function(dir, done) {
  var results = [];
  fs.readdir(dir, function(err, list) {
    if (err) return done(err);
    var i = 0;
    (function next() {
      var file = list[i++];
      if (!file) return done(null, results);
      file = dir + '/' + file;
      fs.stat(file, function(err, stat) {
        if (stat && stat.isDirectory()) {
          walk(file, function(err, res) {
            results = results.concat(res);
            next();
          });
        } else {
          results.push(file);
          next();
        }
      });
    })();
  });
};

walk(filePath, function (err, files) {
    if (err) {
        console.error("Could not list the directory.", err);
        process.exit(1);
    }
        
        files.forEach(function (file, index) {
        var currentPath = file;

        fs.stat(currentPath, function (error, stat) {
            if (error) {
                console.error("Error stating file.", error);
                return;
            }

            if (stat.isFile() && path.extname(currentPath) == '.html') {
                var basename = file.replace(path.extname(currentPath),'');
                basenames.push(basename);
                
                fs.readFile(currentPath, "utf8", function read(err, htmldata) {
                    if (err) {
                        throw err;
                    }
                    
                    //filter files
                    if(!currentPath.includes("googlead3a8d7b4a682812") && !currentPath.includes("install-service-worker")){
                        
                        //fs.rename(currentPath, currentPath.replace(".html", ".amp.html"), function(err) {
                        //    if ( err ) console.log('ERROR: ' + err);
                        //});
                        console.log('optimizing: ' + currentPath);
                        
                        optimizer.transformHtml(htmldata).then(optimizedHtml => {
                            fs.writeFile(currentPath, optimizedHtml, function (err) {
                                if (err) throw err;
                            });
                        });
                    }
                });

                //HTML FILES TEST
                //console.log("'"+currentPath+"' is a file. ("+path.extname(currentPath)+")("+basename+")");

            } else {
                //HTML FILES TEST
                //console.log("'%s' is not an html file.", currentPath);
            }
        });
    });
});`

**Comment by sebastianbenz** [comment]
I'll look into it

**Comment by sebastianbenz** [comment]
This is fixed in v2.8.7. Can you please check wether it works now for you?

**Comment by SimonHogstromRonbol** [comment]
@sebastianbenz with the version update, everything seems to be working as expected, and we are no longer experiencing any errors, thank you :)
