### ISSUE TITLE
AMP Validator within amp-linter needs to be updated

### ISSUE THREAD

**Issue by shishirm** [ampproject/amp-toolbox#1290]
When running the amp-linter, the amp validation step throws the following error,

[{"severity":{"h":"ERROR"},"line":1,"col":0,"message":"The native JavaScript AMPHTML Validator (validator.js) has been turned down. If you are seeing this error, update your tooling to instead load the API compatible WebAssembly AMPHTML Validator (validator_wasm.js) instead.","specUrl":"","code":{"g":"UNKNOWN_CODE"},"params":[]}]

indicating that the amp validator dependency needs to be updated.

**Comment by sebastianbenz** [comment]
This should be fixed with the new 2.8.8 release

**Comment by sebastianbenz** [comment]
Would be great if you could verify that it's working for you now.
