### ISSUE TITLE
node-fetch dependency needs to be updated

### ISSUE THREAD

**Issue by AlineLee** [ampproject/amp-toolbox#1291]
The node-fetch 2.6.1 has a vulnerability issue.

<img width="273" alt="image" src="https://user-images.githubusercontent.com/1765898/153392094-8249bd61-55e2-43ce-bf66-3c725772af21.png">

<img width="175" alt="image" src="https://user-images.githubusercontent.com/1765898/153392535-b1c1bcc1-738c-4a00-8df3-94109235c99c.png">

https://snyk.io/test/npm/node-fetch/2.6.1

**Comment by sebastianbenz** [comment]
Thanks for reporting. Fixed in 2.8.8
