### ISSUE TITLE
AMP linter and Web Story Developer documentation disagree on image sizes

### ISSUE THREAD

**Issue by sdenaro** [ampproject/amp-toolbox#1311]
I am seeing an issue when running amp-linter on the story output of tool described [here](https://github.com/ampproject/amp.dev/issues/6243)

When I run the AMP Linter on the URLs submitted by Pendular.io I see the following error reported about the poster image:

`failed [isAtLeast696x928]`

But the [developer documentation](https://amp.dev/documentation/components/amp-story/#poster-portrait-src-(required)) Says:

```
Portrait: 640px x 853px
Landscape: 853px x 640px
Square: 640px x 640px
Any idea on what we should be doing? Do we need to update lint or our documentation?
```

Any idea what's going on here?

**Comment by sebastianbenz** [comment]
I think the documentation should be the reference. We should update the linter instead.

**Comment by sdenaro** [comment]
It looks [like the ruleset](https://github.com/ampproject/amp-toolbox/blob/74d40a61c55db03c21d94da399e9af6f417ca34f/packages/linter/src/rules/StoryMetadataThumbnailsAreOk.ts) matches the documentation. Is there some reason I am getting `failed [isAtLeast696x928]` ? Let me double check what version I am running on my end.

**Comment by sebastianbenz** [comment]
When I run the latest linter version against the pendular.io story I don't get this error:

` npx @ampproject/toolbox-cli lint https://engine.pendular.io/uploads/amp/415/cad-atl-1638446823.html`

**Comment by sdenaro** [comment]
I am closing this, looks like the issue is resolved locally and doesn't require anything from the linter.

Thanks
