### ISSUE TITLE
Lastest version of the linter just fails

### ISSUE THREAD

**Issue by lmtr0** [ampproject/amp-toolbox#1370]
I try to run the linter against the amp.dev page and I get this error:
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/tokenize' is not defined by "exports" in /home/user/.npm/_npx/53523ddfcc5ce0c2/node_modules/postcss/package.json
```

Please help me, I tried npx, pnpx and bunx, none of them work

**Comment by danielrozenberg** [comment]
@powerivq is this something you can help with?

**Comment by powerivq** [comment]
@lmtr0 Could you inform me what is your nodejs version? Is it LTS?

**Comment by lmtr0** [comment]
node: v20.11.1
deno: 1.46.1
bun: 1.1.10
Operating System: Fedora 40 (Workstation Edition)

@powerivq

**Comment by powerivq** [comment]
@lmtr0 Can you provide an exact reproduction of the error?

**Comment by lmtr0** [comment]
Fun how it just decided to work now :|

**Comment by powerivq** [comment]
Glad to hear!
