### ISSUE TITLE
[update-cache] should use updateCacheApiDomainSuffix

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp-toolbox#153]
We should make sure that our API uses this field.

```
[ { id: 'google',
    name: 'Google AMP Cache',
    docs: 'https://developers.google.com/amp/cache/',
    cacheDomain: 'cdn.ampproject.org',
    updateCacheApiDomainSuffix: 'cdn.ampproject.org',
    thirdPartyFrameDomainSuffix: 'ampproject.net' },
  { id: 'cloudflare',
    name: 'Cloudflare AMP Cache',
    docs: 'https://amp.cloudflare.com/',
    cacheDomain: 'cdn.cloudflare.com',
    updateCacheApiDomainSuffix: 'amp.cloudflare.com',
    thirdPartyFrameDomainSuffix: 'cloudflareamp.net' } ]
```

**Comment by andreban** [comment]
`updateCacheApiDomainSuffix` is what is being used here: 
https://github.com/ampproject/amp-toolbox/blob/master/packages/update-cache/lib/UpdateCacheUrlProvider.js#L46

The demo seems the be using the correct domain as well:
<img width="485" alt="screen shot 2018-11-15 at 9 50 24 am" src="https://user-images.githubusercontent.com/1733592/48544666-00d11c00-e8bc-11e8-9670-8b6e76d3434a.png">

**Comment by sebastianbenz** [comment]
Ah perfect, I wasn't aware
