### ISSUE TITLE
Consider @amp-toolbox npm package scope

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amp-toolbox#220]
Might be worth moving all the `amp-toolbox-*` packages into an `@amptoolbox/*` scope ([more info](https://docs.npmjs.com/creating-and-publishing-scoped-public-packages)) for clarity, and to prevent `amp-toolbox-foo` from being created in the same "namespace". (I don't think there's anything to prevent this at the moment?)

The scopes `@amp`, `@amphtml` or `@ampproject` may be better/worse, perhaps depending on whether [amphtml-validator](https://www.npmjs.com/package/amphtml-validator) is also moved.

**Comment by sebastianbenz** [comment]
Agreed! I like the idea of a generic amphtml scope! 

```
@amphtml/
     validator
     optimizer
     optimizer-express
     cache-list
     cache-update
     runtime-version
     cors
```

@Gregable wdyt about renaming the validator package?

**Comment by Gregable** [comment]
If starting from scratch, I'd be 100% in agreement.

Considering there is a substantial user base, I think it might be disruptive to existing users. Is there a way to essentially `301` all updates / syncs for existing users of an npm package to another path?

**Comment by Gregable** [comment]
I suppose we could alternatively maintain both locations of the npm package too. The validator doesn't get frequent updates due to the fact that it pulls new rules from the network automatically, so this may not be much of a maintenance burden.

**Comment by sebastianbenz** [comment]
I definitely wouldn't want to pull the old version, instead we could [deprecate](https://docs.npmjs.com/cli/deprecate) it to point users to the new version.

**Comment by ithinkihaveacat** [comment]
Closed via https://github.com/ampproject/amp-toolbox/pull/345.
