### ISSUE TITLE
Option to reduce blurry image console output

### ISSUE THREAD

**Issue by NickInSpace** [ampproject/amp-toolbox#221]
Using the optimizer-express package, every image that is successfully rendered with AddBlurryImagePlaceholders is logged to the console - and with longer image urls creates a lot of noise in the logs. Could we add an option to suppress this output?

eg.
AMP Optimizer Adding blurry image placeholder for (src / resolved): https://www.example.com/longurl/image.jpg https://www.example.com/longurl/image.jpg

**Comment by sebastianbenz** [comment]
That totally makes sense. My suggestion would be:

* when the log level is set to `verbose`
   * **if** an image could not be resolved: `AMP Optimizer could not add blurry image placeholder for (src / resolved): /longurl/image.jpg https://www.example.com/longurl/image.jpg`
   *  **if** the image could be resolved: `AMP Optimizer added blurry image placeholder for: /longurl/image.jpg` 
* when the log level is set to > `verbose`:
   * **if** an image could not be resolved log a shorter message: `AMP Optimizer could not add blurry image placeholder for: /longurl/image.jpg [enable verbose mode to debug]` 
   * **if** an image could be resolved don't log anything

@NickInSpace Would that work for you?

**Comment by NickInSpace** [comment]
Thanks @sebastianbenz, that sounds like it would work perfectly.

**Comment by sebastianbenz** [comment]
Just made a release containing this change.
