### ISSUE TITLE
[optimizer] support brotli compression

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp-toolbox#241]
The AMP Cache has started serving the AMP runtime with brotli compression enabled:

```
https://cdn.ampproject.org/rtv/011902271810270/v0/amp-accordion-0.1.js.br
```

We should also support this for the AMP optimizer. 

This requires two changes:

1. optimizer needs an option to rewrite amp runtime urls to use brotli compression.
2. optimizer-express: needs to serve different versions depending on whether the UA accepts `br`: `accept-encoding: gzip, deflate, br`. This probably needs to be opt-in as it also requires adjusting the caching layer.

//cc @jridgewell @honeybadgerdontcare is there anything else that we should be doing?

**Comment by ithinkihaveacat** [comment]
Do you know why it's being served from a different URL? Very unusual and inconvenient! I don't know any reason to do that unless there's some subtle content negotiation going on (i.e. beyond the client indicating that it can handle brotli via `accept-encoding: br`), which might be difficult and/or unwise to replicate in the optimizer.

**Comment by jridgewell** [comment]
No, please do not do this. The `.js.br` serving is a temporary hack, and the serving infrastructure is being fixed so that we'll be able serve both gzip and brotli responses from the regular `.js` url (b/122826290).

Support for `.js.br` won't be continued.

**Comment by sebastianbenz** [comment]
Ah - even better. Thanks!
