### ISSUE TITLE
Add _top to a links to match Google AMP cache transformations 

### ISSUE THREAD

**Issue by bjalford** [ampproject/amp-toolbox#25]
It seems that Google AMP Cache add target="_top" to all a links. Review if desired for amp-toolbox and if so implement a transformation so that it matches the AMP Cache one.

**Comment by sebastianbenz** [comment]
Interesting. So far we've been aiming AMP SSR towards canonical AMP sites
in which case this transformation wouldn't make as much sense - or am I
missing something?

**Comment by andreban** [comment]
Looks like `target="_top"` is there to make the AMP served from the Cache work well with the AMP Viewers. 

If there's a use-case where developers may want to use the Server-Side-Rendered AMPs from inside the viewers, it may make sense.
