### ISSUE TITLE
Add support for 'intrinsic' image layout 

### ISSUE THREAD

**Issue by NickInSpace** [ampproject/amp-toolbox#264]
Using amp-optimizer-express I'm getting the error:

```
AMP Optimizer cannot perform SSR: unsupported layout intrinsic
AMP Optimizer cannot remove boilerplate: unsupported layout
```

But I can't find any reason why it wouldn't be supported according to: https://www.ampproject.org/docs/design/responsive/control_layout

**Comment by sebastianbenz** [comment]
@honeybadgerdontcare is there a specific reason why intrinsic layout is currently not supported for AMP SSR?

**Comment by honeybadgerdontcare** [comment]
@jpettitt for more info. when it was released it was automatically not supported, so that it could be refined. it might be stable enough now to support it for applying layout.

**Comment by NickInSpace** [comment]
@sebastianbenz any update on this?

**Comment by honeybadgerdontcare** [comment]
Here's the original issue #17686 for supporting intrinsic in SSR context.
