### ISSUE TITLE
amp-toolbox-cors for serverless

### ISSUE THREAD

**Issue by gkemp94** [ampproject/amp-toolbox#278]
As a feature request, it would be great if there were serverless version of some of the cors middleware, something that can be used with middy.

**Comment by sebastianbenz** [comment]
That's interesting. Middy doesn't happen to be based on [connect](https://www.npmjs.com/package/connect)? The only thing the cors middleware needs is a response and request object. If these are supported or could be easily wrapped, an integration should be pretty easy.

**Comment by gkemp94** [comment]
@sebastianbenz I don't think it is. I think the challenge is that you aren't provided a req & res object with aws, just an event containing the headers, so I think they'll have to be two aspects, the "before" which captures the headers and verifies the request, and the "after" which transforms the returned object and adds the correct headers. I also know that middy is targeted at AWS, I'm not sure if there a solution that would might be platform agnostic.

**Comment by sebastianbenz** [comment]
Hm OK. What we definitely should to is expose a generic API that makes it easy to integrate other platforms. Something along the lines of:

```
const ampCors = ...;
const request = {
  url: "https://example.com?___amp-source...",
  headers: {
     "amp-same-origin" true,
    ...
   }
};
const callback = {
   setHeader: (key, value) => { ... },
   setStatus: (status, message) => { ... },
}
ampCors.handle(request, callback, options);
```

**Comment by gkemp94** [comment]
Yeah that sounds perfect!

**Comment by sebastianbenz** [comment]
Since the AMP CORS protocol is no longer needed (see https://github.com/ampproject/amphtml/issues/22136), I don't think this feature is as critical. Closing for now.
