### ISSUE TITLE
Deprecate the amp-toolbox-* packages

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amp-toolbox#360]
The modules were moved into the @ampproject scope via https://github.com/ampproject/amp-toolbox/pull/345. There's a few places this deprecation/migration should be flagged:

- Using https://docs.npmjs.com/cli/deprecate
- On npmjs.com module pages e.g.https://www.npmjs.com/package/amp-toolbox-optimizer

**Comment by sebastianbenz** [comment]
done

**Comment by sebastianbenz** [comment]
```
$ npm i amp-toolbox-ssr
npm WARN deprecated amp-toolbox-ssr@0.1.1: "amp-toolbox-ssr has been moved to @ampproject/toolbox-optimizer"
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

+ amp-toolbox-ssr@0.1.1
added 3 packages from 2 contributors and audited 244 packages in 3.156s
found 0 vulnerabilities
```
