### ISSUE TITLE
[linter] Pretty print checks

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp-toolbox#384]
Currently, the checks are written as one word without any way to differentiate between words. 

I'd consider this a blocking easy for the first official release.

**Comment by sebastianbenz** [comment]
For example:

```
correct amp-img heigths and widths (PASS)
```

instead of

```
ampimgheightwidthisok  (PASS)
```

**Comment by ithinkihaveacat** [comment]
I'll work on this. It's not too difficult: the Rule class [includes fields](https://github.com/ampproject/amp-toolbox/blob/8a65a0254e883e29373ababa4dc20bebdc0444d3/packages/linter/src/rule.ts#L11-L12) that were intended to store this (and related) info.
