### ISSUE TITLE
Fix publish of @ampproject/toolbox-linter

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amp-toolbox#395]
It appears https://github.com/ampproject/amp-toolbox/pull/358 didn't work, which means `@ampproject/toolbox-linter` does work--we need to republish it.

For $reasons, toolbox-linter uses `@pika/pack` for publishing. This generates the package to be published in the `pkg` directory. (i.e. it generates `pkg/package.json` from `package.json`.)

Historically, lerna did no support publishing from any directory other than the root, however this was supposedly changed in https://github.com/lerna/lerna/pull/2109, and this repo was updated to support this format in #305 

However, the latest published versions of @ampproject/toolbox-linter (in fact all published versions) are "bad": they don't contain the contents of the `pkg` directory. In particular, there is no `main` key.

Actual format:

https://unpkg.com/@ampproject/toolbox-linter@1.0.0-beta.4/

Expected format:

https://unpkg.com/amp-toolbox-linter@0.0.17/

(Compare `package.json` files.)

I'm still looking into why this happened. Are we using a version of lerna that supports `publishConfig`?

**Comment by sebastianbenz** [comment]
Fixed by #402
