### ISSUE TITLE
[optimizer] creating cachable versions of a web site on a different URL the CORS issue

### ISSUE THREAD

**Issue by QES** [ampproject/amp-toolbox#41]
Hi,

Although this may not have been the original intent of this tool it is, unfortunately, the way my infrastructure is built.

We have our canonical pages on https://www.sportsmole.co.uk and our AMP pages on https://amp.sportsmole.co.uk with a front-end cache (Varnish 5.2.1) that sends mobile/tablet (touch) users to the AMP pages and desktop users to their site of choice.

I am keen to add to the mix the idea of pre-rendering in the same way that Google does with its amp cache and in the same way that others do (CloudFlare).

As a first test I decided to use the amp-toolbox optimizer to create copies of pages and place them on a separate URL http://cache.sportsmole.co.uk/ to see if I can get them to work and immediately I had an issue of the CORS config. (the https version can be found at https://d23hbvp42pjqt1.cloudfront.net/index.html)

Https://cache.sportsmole.co.uk is on an amazon S3 bucket for the moment and the CORS config is set to:

```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <ExposeHeader>AMP-Redirect-To,AMP-Access-Control-Allow-Source-Origin</ExposeHeader>
    <AllowedHeader>Content-Type,Content-Length,Accept-Encoding,X-CSRF-Token</AllowedHeader>
</CORSRule>
</CORSConfiguration>
```

However when I try to load the page 

```
Failed to load https://amp.sportsmole.co.uk/amp_ping/amp-fu2d6CFNdnwE9PNbB4sNDw0.93244027565443541/?rid=amp-fu2d6CFNdnwE9PNbB4sNDw&uri=https%3A%2F%2Fd23hbvp42pjqt1.cloudfront.net%2Findex.html&pass=PIK&_=0.22654620531193914&host=amp.sportsmole.co.uk&ht=https:&FB=OK&ref=https%3A%2F%2Fd23hbvp42pjqt1.cloudfront.net%2Findex.html&dynamic&__amp_source_origin=https%3A%2F%2Fd23hbvp42pjqt1.cloudfront.net: The 'Access-Control-Allow-Origin' header has a value 'https://amp.sportsmole.co.uk' that is not equal to the supplied origin. Origin 'https://d23hbvp42pjqt1.cloudfront.net' is therefore not allowed access. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Are there any tips on doing this kind of thing or is it out of hte scope of the project it is what the google cache does after all?

Thans
Alan

**Comment by andreban** [comment]
The "Access-Control-Allow-Origin" header on the response is being returned as "https://amp.sportsmole.co.uk". Since this is being served from "https://d23hbvp42pjqt1.cloudfront.net/index.html", the CORS validation fails.

I noticed you added a setup for the  CORS rules o  https://cache.sportsmole.co.uk, but it needs to be set for https://amp.sportsmole.co.uk , which is the domain serving the cross-origin request.

<img width="1255" alt="screen shot 2018-02-22 at 10 07 06 am" src="https://user-images.githubusercontent.com/1733592/36532302-3bc56706-17b8-11e8-9c0a-18d2c03ca3e0.png">

**Comment by QES** [comment]
Thanks - that makes sense but if this tool is supposed to change the object to be able to be used in a cache this would imply that it MUST be the same URL as it doesn't change these elements into ones that relate to the new URL that is being used (does that make sense?)

The Google (and other) AMP Caches I assume must be making these changes so that the loaded pages load correctly and have the correct CORS setting.

Is this something that should be added to this tool?

**Comment by QES** [comment]
So the key problem is the S3 server doesn't send an Origin Header as far as I can tell by default so none of the cors elements will work as expected.  Looking to see how this can be worked around.

**Comment by andreban** [comment]
This seems to be a AMP CORS / S3 related question. Do you mind moving this to StackOverflow?

**Comment by QES** [comment]
Hi @andreban will do - through the original CORS issues, I think I have solved but not the underlying question as to getting this to work.

So everything works as expected on the amproject/google cache but on my cache I don't seem to be loading enough of the amp-access module to get any of the hidden elements to hide.

**Comment by andreban** [comment]
Would you have a link I can test or instructions on how to reproduce the issue?

**Comment by QES** [comment]
So I created some test pages at:

https://cache.sportsmole.co.uk/index.html

the basic page is loading OK at the moment there are complaints from the serviceworker (which I don't expect to load at present) and I'm still getting a few CORS errors but not from the files being loaded from the amp-list elements or amp-access elements which seem to be returning valid data.

The errors seem to be in service.js and log.js any ideas?

Alan

l```
og.js:162 Authorization failed:  Error: Returned AMP-Access-Control-Allow-Source-Origin is not equal to the current: https://amp.sportsmole.co.uk vs https://cache.sportsmole.co.uk​​​
    at oa.f.assert (log.js:318)
    at action-impl.js:485
    at <anonymous>
pa @ log.js:162
f.Ne @ log.js:217
f.error @ log.js:233
(anonymous) @ amp-access.js:482
Promise.catch (async)
wb @ amp-access.js:476
(anonymous) @ amp-access.js:369
Xb @ document-register-element.node.js:446
O @ document-register-element.node.js:99
(anonymous) @ viewport-impl.js:1123
gl @ viewport-impl.js:1127
al @ viewport-impl.js:1123
$k @ viewport-impl.js:873
(anonymous) @ amp-access.js:1002
f @ amp-access.js:1001
(anonymous) @ viewer-impl.js:298
Promise.then (async)
amp-access @ viewer-impl.js:282
Vf @ url-replacements-impl.js:907
(anonymous) @ url-replacements-impl.js:936
Promise.then (async)
Sf @ url-replacements-impl.js:930
Qf @ url-replacements-impl.js:880
c @ viewer-impl.js:320
(anonymous) @ viewer-impl.js:393
(anonymous) @ resources-impl.js:1574
setTimeout (async)
f.delay @ resources-impl.js:1574
Cl @ viewer-impl.js:555
Al @ viewer-impl.js:382
Dl @ viewer-impl.js:425
g @ viewer-impl.js:888
Vf @ url-replacements-impl.js:907
Rf.Oe @ url-replacements-impl.js:1036
(anonymous) @ url-replacements-impl.js:1040
Promise.then (async)
Xf @ url-replacements-impl.js:1040
Rf.Ma @ url.js:72
(anonymous) @ url-replacements-impl.js:1012
Promise.then (async)
Tf @ url-replacements-impl.js:1009
Qf @ url-replacements-impl.js:880
(anonymous) @ viewer-impl.js:886
Kd @ service.js:459
initial @ viewer-impl.js:857
Vf @ url-replacements-impl.js:907
Rf.Oe @ url-replacements-impl.js:1036
(anonymous) @ url-replacements-impl.js:1040
Promise.then (async)
Xf @ url-replacements-impl.js:1040
Rf.Ma @ url.js:72
(anonymous) @ url-replacements-impl.js:1012
Promise.then (async)
Tf @ url-replacements-impl.js:1009
Qf @ url-replacements-impl.js:880
(anonymous) @ viewer-impl.js:837
(anonymous) @ viewer-impl.js:950
service.js:255 Returned AMP-Access-Control-Allow-Source-Origin is not equal to the current: https://amp.sportsmole.co.uk vs https://cache.sportsmole.co.uk
ce @ service.js:255
(anonymous) @ viewer-impl.js:178
f.assert @ log.js:324
(anonymous) @ action-impl.js:485
Promise.then (async)
Gh @ action-impl.js:477
f.fetch @ action-impl.js:751
Mh.fetch @ action-impl.js:982
f.fetchJson @ action-impl.js:676
(anonymous) @ batched-json.js:79
Promise.then (async)
Q @ batched-json.js:59
V @ batched-json.js:45
S @ amp-list.js:166
push.f.R.layoutCallback @ amp-list.js:91
Cg.b.layoutCallback @ custom-element.js:572
f.startLayout @ base-element.js:896
h @ resources-impl.js:1155
Ki.setState @ history-impl.js:227
f.doPass @ resources-impl.js:249
(anonymous) @ history-impl.js:443
Hf.tc @ url-replacements-impl.js:618
Hf.$f @ services.js:267
(anonymous) @ resources-impl.js:1574
setTimeout (async)
f.delay @ resources-impl.js:1574
Hf.schedule @ url-replacements-impl.js:618
f.schedulePass @ task-queue.js:115
f.Ma @ resources-impl.js:1054
qj @ resources-impl.js:976
yj @ resources-impl.js:552
h @ resources-impl.js:1139
Ki.setState @ history-impl.js:227
f.doPass @ resources-impl.js:249
(anonymous) @ history-impl.js:443
Hf.tc @ url-replacements-impl.js:618
Hf.$f @ services.js:267
(anonymous) @ resources-impl.js:1574
Promise.then (async)
f.delay @ resources-impl.js:1574
Hf.schedule @ url-replacements-impl.js:618
f.schedulePass @ task-queue.js:115
(anonymous) @ history-impl.js:443
Hf.tc @ url-replacements-impl.js:618
Hf.$f @ services.js:267
(anonymous) @ resources-impl.js:1574
Promise.then (async)
f.delay @ resources-impl.js:1574
Hf.schedule @ url-replacements-impl.js:618
a @ history-impl.js:603
(anonymous) @ history-impl.js:609
Promise.then (async)
ej @ history-impl.js:591
Xb @ document-register-element.node.js:446
K @ document-register-element.node.js:371
$c @ document-register-element.node.js:947
Fj @ resources-impl.js:1310
Xb @ document-register-element.node.js:446
O @ document-register-element.node.js:99
(anonymous) @ viewer-impl.js:873
Vf @ url-replacements-impl.js:907
Rf.Oe @ url-replacements-impl.js:1036
(anonymous) @ url-replacements-impl.js:1040
Promise.then (async)
Xf @ url-replacements-impl.js:1040
Rf.Ma @ url.js:72
(anonymous) @ url-replacements-impl.js:1012
Promise.then (async)
Tf @ url-replacements-impl.js:1009
Qf @ url-replacements-impl.js:880
(anonymous) @ viewer-impl.js:873
Kd @ service.js:459
initial @ viewer-impl.js:857
Vf @ url-replacements-impl.js:907
Rf.Oe @ url-replacements-impl.js:1036
(anonymous) @ url-replacements-impl.js:1040
Promise.then (async)
Xf @ url-replacements-impl.js:1040
Rf.Ma @ url.js:72
(anonymous) @ url-replacements-impl.js:1012
Promise.then (async)
Tf @ url-replacements-impl.js:1009
Qf @ url-replacements-impl.js:880
(anonymous) @ viewer-impl.js:837
(anonymous) @ viewer-impl.js:950
log.js:318 Uncaught (in promise) Error: Error fetching amp-list: Returned AMP-Access-Control-Allow-Source-Origin is not equal to the current: https://amp.sportsmole.co.uk vs https://cache.sportsmole.co.uk​​​
    at oa.f.assert (log.js:318)
    at action-impl.js:485
    at <anonymous>
f.assert @ log.js:318
(anonymous) @ action-impl.js:485
Promise.then (async)
Mh.fetch @ action-impl.js:982
f.fetchJson @ action-impl.js:676
(anonymous) @ batched-json.js:79
Promise.then (async)
Q @ batched-json.js:59
V @ batched-json.js:45
S @ amp-list.js:166
push.f.R.layoutCallback @ amp-list.js:91
Cg.b.layoutCallback @ custom-element.js:572
f.startLayout @ base-element.js:896
h @ resources-impl.js:1155
Ki.setState @ history-impl.js:227
f.doPass @ resources-impl.js:249
(anonymous) @ history-impl.js:443
Hf.tc @ url-replacements-impl.js:618
Hf.$f @ services.js:267
(anonymous) @ resources-impl.js:1574
setTimeout (async)
f.delay @ resources-impl.js:1574
Hf.schedule @ url-replacements-impl.js:618
f.schedulePass @ task-queue.js:115
f.Ma @ resources-impl.js:1054
qj @ resources-impl.js:976
yj @ resources-impl.js:552
h @ resources-impl.js:1139
Ki.setState @ history-impl.js:227
f.doPass @ resources-impl.js:249
(anonymous) @ history-impl.js:443
Hf.tc @ url-replacements-impl.js:618
Hf.$f @ services.js:267
(anonymous) @ resources-impl.js:1574
Promise.then (async)
f.delay @ resources-impl.js:1574
Hf.schedule @ url-replacements-impl.js:618
f.schedulePass @ task-queue.js:115
(anonymous) @ history-impl.js:443
Hf.tc @ url-replacements-impl.js:618
Hf.$f @ services.js:267
(anonymous) @ resources-impl.js:1574
Promise.then (async)
f.delay @ resources-impl.js:1574
Hf.schedule @ url-replacements-impl.js:618
a @ history-impl.js:603
(anonymous) @ history-impl.js:609
Promise.then (async)
ej @ history-impl.js:591
Xb @ document-register-element.node.js:446
K @ document-register-element.node.js:371
$c @ document-register-element.node.js:947
Fj @ resources-impl.js:1310
Xb @ document-register-element.node.js:446
O @ document-register-element.node.js:99
(anonymous) @ viewer-impl.js:873
Vf @ url-replacements-impl.js:907
Rf.Oe @ url-replacements-impl.js:1036
(anonymous) @ url-replacements-impl.js:1040
Promise.then (async)
Xf @ url-replacements-impl.js:1040
Rf.Ma @ url.js:72
(anonymous) @ url-replacements-impl.js:1012
Promise.then (async)
Tf @ url-replacements-impl.js:1009
Qf @ url-replacements-impl.js:880
(anonymous) @ viewer-impl.js:873
Kd @ service.js:459
initial @ viewer-impl.js:857
Vf @ url-replacements-impl.js:907
Rf.Oe @ url-replacements-impl.js:1036
(anonymous) @ url-replacements-impl.js:1040
Promise.then (async)
Xf @ url-replacements-impl.js:1040
Rf.Ma @ url.js:72
(anonymous) @ url-replacements-impl.js:1012
Promise.then (async)
Tf @ url-replacements-impl.js:1009
Qf @ url-replacements-impl.js:880
(anonymous) @ viewer-impl.js:837
(anonymous) @ viewer-impl.js:950
service.js:255 Returned AMP-Access-Control-Allow-Source-Origin is not equal to the current: https://amp.sportsmole.co.uk vs https://cache.sportsmole.co.uk
```

**Comment by QES** [comment]
Curiously if I look at the S3 bucket directly then it now seems to be working.

https://s3-eu-west-1.amazonaws.com/cache.sportsmole.co.uk/amp.sportsmole.co.uk.html

But via an intermediate tool to allow me to use https on my domain then it fails as above will investigate futher.

Thanks for your help and guidence.

**Comment by andreban** [comment]
The errors described seem to be CORS errors. Here's more information on [CORS Requests and AMP](https://www.ampproject.org/docs/fundamentals/amp-cors-requests#cors-security-in-amp). I'd recommend testing the non-optimized AMP on the same server first and solve the issues, and then try out the optimized version. 

I'm closing the bug, as the errors seem to be unrelated to the optimizer. Please, re-open if the issues persist after making the non-optimized version work.

**Comment by QES** [comment]
Hi @andreban you can compare similar examples at there are some differences caused by the optimizer between pages depending on the elements being used but it isn't consistent.  These are all copies of the site sitting on an S3 bucket (indexes have added text to say they are error pages) but otherwise, the pages should be the same but they don't always work the same.  Many pages work perfectly when converted but some seem to have errors.  I can't see how the errors are caused by the conversion but equally I'm not sure why the same HTML is otherwise fine. 

http://cache.sportsmole.co.uk.s3-website-eu-west-1.amazonaws.com/football/spurs/injury-news/news/alderweireld-resumes-first-team-training_320481.html
http://amp.sportsmole.co.uk.s3-website-eu-west-1.amazonaws.com/football/spurs/injury-news/news/alderweireld-resumes-first-team-training_320481.html

http://cache.sportsmole.co.uk.s3-website-eu-west-1.amazonaws.com/index.html
http://amp.sportsmole.co.uk.s3-website-eu-west-1.amazonaws.com/index.html

http://cache.sportsmole.co.uk.s3-website-eu-west-1.amazonaws.com/headlines/
http://amp.sportsmole.co.uk.s3-website-eu-west-1.amazonaws.com/headlines/

http://cache.sportsmole.co.uk.s3-website-eu-west-1.amazonaws.com/rugby-union/england/six-nations/news/jones-farrell-must-be-aggressive_320487.html
http://amp.sportsmole.co.uk.s3-website-eu-west-1.amazonaws.com/rugby-union/england/six-nations/news/jones-farrell-must-be-aggressive_320487.html

http://cache.sportsmole.co.uk.s3-website-eu-west-1.amazonaws.com/football/spurs/injury-news/news/alderweireld-resumes-first-team-training_320481.html
http://amp.sportsmole.co.uk.s3-website-eu-west-1.amazonaws.com/football/spurs/injury-news/news/alderweireld-resumes-first-team-training_320481.html
