### ISSUE TITLE
[update-cache] Implement CLI for update-cache

### ISSUE THREAD

**Issue by andreban** [ampproject/amp-toolbox#49]
Implement CLI for the library update-cache. Usage should be something like the following:

`update-cache https://amp.example.com privateKey.pem`

**Comment by sebastianbenz** [comment]
Should we have multiple feature specific CLIs (e.g. update-cache, covert URL,...) or one CLI for all of amp-toolbox?

**Comment by andreban** [comment]
If idea would be that installing `amp-toolbox-cli` would install the `amp-toolbox-optimizer` and `amp-toolbox-update-cache` commands, I think a centralised CLI makes sense.

**Comment by andreban** [comment]
Closed via #72
