### ISSUE TITLE
Consider moving preload link tags to top of markup

### ISSUE THREAD

**Issue by bjalford** [ampproject/amp-toolbox#50]
Wondering whether there's a performance benefit of moving  link preload tags to the top of the document. 

V0 loads quickly but other preloads e.g. fonts which we put in are after our custom CSS and the optimiser moves elements around so we can't alter the position of the preload tags. 

Not sure how much impact but from the test below looks like the font could start 0.5 seconds earlier at same time as v0?

Test results:
http://www.webpagetest.org/video/compare.php?tests=180530_XG_e4621d79c21b9eed5a9444c6126f25ef-r:2-c:0

**Comment by andreban** [comment]
Should we change the `OptimizeHeaderTransformer` to move existing preloads to the top?

#55 improves the placement of the auto-generated preloads for Google Fonts (GoogleFontsPreconnect), since it runs after the OptimizeHeaderTransformer.

**Comment by andreban** [comment]
We'd may also want to change `RewriteAmpUrls` and `PreloadImages` transformers to do the same.

**Comment by sebastianbenz** [comment]
Can we make the OptimizeHeaderTransformer move all preloads? I don't see a reason why GoogleFontsPreconnect needs to run after OptimizeHeaderTransformer.

**Comment by andreban** [comment]
Yes, I think `OptimizeHeaderTransformer`should move all preloads. But I also think that a transformer that injects a preload should add it to the right place by default and not rely on the `OptimizeHeaderTransformer`behaviour (avoid dependency on running in the right order) .

**Comment by andreban** [comment]
#56 changes `ReorderHeaderTransformer`

**Comment by andreban** [comment]
#58 and #59 change `PreloadImages` and `RewriteAmpUrls`

**Comment by andreban** [comment]
Deployed in version 0.3.0
