### ISSUE TITLE
Improve boilerplate inline CSS handling when self-hosting AMP runtime

### ISSUE THREAD

**Issue by mattwomple** [ampproject/amp-toolbox#550]
The transformer currently inlines boilerplate CSS based on the following logic: if version specified, get boilerplate from `cdn.ampproject.org/rtv/{rtv}/v0.css`, otherwise get boilerplate from `cdn.ampproject.org/v0.css`:

https://github.com/ampproject/amp-toolbox/blob/c92d6023ea4c9edadff593742a992da2b400a75d/packages/optimizer/lib/transformers/AmpBoilerplateTransformer.js#L85-L90

If self-hosting the AMP runtime, it makes sense to reference the self-hosted runtime for boilerplate CSS. This is especially relevant when no version is specified and it should not be assumed that `www.example.com/v0.css` is the same as `cdn.ampproject.org/v0.css`.

This change would introduce a caveat -- whereas it is possible to optimize AMP pages today without the self-hosted runtime being available, either that possibility would have to be nixed, or a fallback to `cdn.ampproject.org` should be allowed.

**Comment by mattwomple** [comment]
Additional discussion: https://github.com/ampproject/amp-toolbox/pull/517#issuecomment-542315626
Relates to: https://github.com/ampproject/amphtml/issues/25873

/cc @sebastianbenz

**Comment by sebastianbenz** [comment]
Good point. Just to be sure: are we only talking about the non-RTV v0.js branch or should v0.css always be downloaded form the runtime host?

We probably need a third option as well for static sites where it needs to be possible to pass the contents of v0.css via parameter at build time.

**Comment by mattwomple** [comment]
I was considering both versioned and non-versioned CSS could come from the runtime host. This does raise a concern, though:

We might need to check with the validators team on this one. If inlined boilerplate CSS doesn't come from cdn.ampproject.org, then it would have to be re-written before the AMP page could be hosted by AMP caches (maybe this happens already?), otherwise publishers could sneak-in disallowed CSS.

**Comment by sebastianbenz** [comment]
> If inlined boilerplate CSS doesn't come from cdn.ampproject.org, then it would have to be re-written before the AMP page could be hosted by AMP caches
I've added this to the self-hosting design doc
