### ISSUE TITLE
Optimizer should deal with angle-bracket delimiters

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp-toolbox#599]
Apparently [certain strange people who will remain nameless](https://github.com/ampproject/samples/pull/235) are running the optimizer on HTML templates which still contain delimiters like `<%` and `>%`. Is this a good idea? Maybe not. But the optimizer currently treats such delimiters in a way that's unexpected, simply transforming them from things like this:

`<h2>Reviews (<%ReviewCount%>)</h2>`

to things like this:

`<h2>Reviews (<%reviewcount%>)</%reviewcount%></h2>`

no doubt because the HTML parser wants to transform the delimiters into valid HTML.

I'd suggest one of the following:

1. Pre-scan HTML for such delimiters, and issue a warning
1. Allow users to specify a template delimiter that the optimizer should ignore.

The second option might mean preprocessing the HTML to replace these delimiters with something that doesn't resemble HTML tags, then postprocessing it to stick them back in. I'm not saying this is a neat solution. I'm just suggesting a possible quick fix.

Perhaps there is a third solution? I'm personally happy with anything that doesn't simply transform the HTML in a way that's undesired, then leave it.

**Comment by sebastianbenz** [comment]
Closing as WAI. Feel free to re-open in case there are more cases where this is a problem
