### ISSUE TITLE
Optional Transformer: Elevate resource hints to header

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-toolbox#607]
If we prepare a response in WP and the header has not yet been sent, we could run an additional transformer to elevate the resource hints (`<link>` elements in head) to the header as `Link: ...` entries: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Link

This would have these resource hints be active even when a URL from our origin is only sent as header for a prefetch.

This is done by the Amp package for signed exchanges: https://github.com/ampproject/amppackager/blob/cc38c5fad40fc603119a298700820b97a4f0c54f/transformer/transformer.go#L194

I'm unsure whether that would be the case and whether we'd actually profit from this.

**Comment by sebastianbenz** [comment]
Interesting. Is there a benefit for non SXG packages?

>

**Comment by schlessera** [comment]
TBH, I don't know. I'm unsure whether header-only requests would even hit a WordPress site. But I think it might be worth exploring at some point.

**Comment by schlessera** [comment]
Oh...

I just realized I created this issue in the wrong repository. This was meant to go into `ampproject/amp-wp` instead. 🙃

Sorry for the confusion, I'll recreate it in the correct repo...
