### ISSUE TITLE
Feature request: Support LTS as runtime version in AMP Optimizer

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amp-toolbox#629]
See https://github.com/ampproject/amphtml/blob/master/contributing/lts-release.md

/cc @sebastianbenz @nainar

**Comment by rcebulko** [comment]
Publishers can opt into LTS by prepending script tag sources with `/lts`, ex. `https://cdn.ampproject.org/lts/v0.js`. There are two ways this could be incorporated into AMP Optimizer, and either or both could be useful.

1. Augment `RuntimeVersion` to support providing the LTS RTV

The section on [Versioned AMP Runtime](https://github.com/ampproject/amp-toolbox/tree/master/packages/optimizer#versioned-amp-runtime) shows publishers how to use the `RuntimeVersion` class to pull the latest Stable or Beta (names outdated, see https://github.com/ampproject/amphtml/issues/25560) RTV and provide that version to the transformer. The https://cdn.ampproject.org/rtv/metadata endpoint now includes a `ltsRuntimeVersion` property which could be used to support an `{ lts: true }` option provided to `RuntimeVercsion` (note that this would have to be mutually exclusive with `{ canary: true }`.

> On a side note, the term "canary" was overloaded and has since been dropped in favor of Beta in most official documentation and communications. It may be worth updating the AMP Optimizer to reflect these changes.

This would allow publishers who use the AMP Optimizer frequently to provide LTS as an option and continuously have their AMP URLs rewritting to RTV-locked versions, each time using the current LTS RTV. This has the typical cache benefits of RTV-locked URLs

2. Augment `RewriteAmpUrls` to support the unversioned LTS runtime

Publishers may wish to use the LTS runtime and extensions without re-running the AMP Optimizer for new LTS releases or cherry-picks. The `RewriteAmpUrls` transformer could be modified to allow rewriting from unversioned standard AMP URLs to unversioned LTS URLs (ex. `https://cdn.ampproject.org/v0.js` --> `https://cdn.ampproject.org/lts/v0.js`). LTS unversioned URLs have better cache behavior, as their lifetime is expected to be one months instead of one week (but not as long as RTV URLs, which are expected never to change).

**Comment by rcebulko** [comment]
Bumping this @nainar @sebastianbenz

**Comment by sebastianbenz** [comment]
2) definitely makes sense and we should add this. 1) Would require validator support first (afaik RTV URLs are not supported). This might happen as part of runtime self hosting.

**Comment by rcebulko** [comment]
@sebastianbenz Re: 1), I'm not sure if the validator is applicable here? Currently, as far as I can tell, the Optimizer rewrites unversioned URLs to RTV urls already, using the standard runtime version. I'm not certain how the validator treats this, but I expect that writing LTS to an RTV-locked URL would be treated similarly already?

**Comment by mdmower** [comment]
It looks like the validator has support for LTS URLs:
- [Original AMP page](https://ampdemo.cmphys.com/amp-sh/standard-amp.html) (✔️ [pass](https://validator.ampproject.org/#url=https%3A%2F%2Fampdemo.cmphys.com%2Famp-sh%2Fstandard-amp.html))
- [Optimized AMP page](https://ampdemo.cmphys.com/amp-sh/standard-opt.html) ([✔️ pass](https://validator.ampproject.org/#url=https%3A%2F%2Fampdemo.cmphys.com%2Famp-sh%2Fstandard-opt-lts.html))
- [Optimized AMP page with LTS URLs](https://ampdemo.cmphys.com/amp-sh/standard-opt-lts.html) ([✔️ pass](https://validator.ampproject.org/#url=https%3A%2F%2Fampdemo.cmphys.com%2Famp-sh%2Fstandard-opt-lts.html))
- [Optimized AMP page with RTV-specific URLs](https://ampdemo.cmphys.com/amp-sh/standard-opt-rtv.html) ([❌ fail](https://validator.ampproject.org/#url=https%3A%2F%2Fampdemo.cmphys.com%2Famp-sh%2Fstandard-opt-rtv.html))

**Comment by rcebulko** [comment]
Yes, `/lts/v0.js` and pals are valid AMP. RTV-locked URLs are not, but I think they may be allowed in the output of the AMP Optimizer? Not certain on that.

**Comment by mdmower** [comment]
> RTV-locked URLs are not, but I think they may be allowed in the output of the AMP Optimizer? Not certain on that.

Yes, that's the _Optimized AMP page with RTV-specific URLs (x fail)_ case in my previous comment. I hope to have #691 wrapped up this week, so LTS will be supported soon.
