### ISSUE TITLE
[cli] Provide a command for downloading a specific AMP release

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp-toolbox#642]
Examples:

```
amp download --dest /dist
amp download --rtv=1234567 
```

Approach:

* fetch `https://cdn.ampproject.org/files.txt`
* download all listed files into the target dir
* option to auto-patch amp-geo:  search for RegEx `/[a-zA-Z]{2} {26}/` and replace with string `{{AMP_ISO_COUNTRY_HOTPATCH}}`.

**Comment by mdmower** [comment]
As a heads up, I've started work on this feature:
https://github.com/mdmower/amp-toolbox/commits/pr-download

It works, but does not have documentation yet.
