### ISSUE TITLE
Support preload images with srcset

### ISSUE THREAD

**Issue by bjalford** [ampproject/amp-toolbox#65]
Seems amp-img with srcset are ignored in the preload images optimisation. 

Would require this first: https://github.com/ampproject/amp-toolbox/issues/63

**Comment by sebastianbenz** [comment]
We don't support srcset as it's not supported by preload. I'm not aware of any workarounds.

**Comment by bjalford** [comment]
Fair enough. Probably best for publisher to implement their own preloads for images. Thanks!
