### ISSUE TITLE
ampRuntimeVersion is ignored if both ampRuntimeVersion and ampUrlPrefix are specified.

### ISSUE THREAD

**Issue by yosuke-furukawa** [ampproject/amp-toolbox#721]
We are sending a PR to zeit/next.js for upgrading amp-optimizer latest version.
https://github.com/zeit/next.js/pull/12039

But some tests are failed. I don't understand why but ampRuntimeVersion and ampUrlPrefix are specified in `next.config.js`. 

```
module.exports = {
  experimental: {
    amp: {
      optimizer: {
        ampRuntimeVersion: '001515617716922',
        ampUrlPrefix: '/amp',
        verbose: true,
      },
      skipValidation: true,
    },
  },
}
```

https://github.com/zeit/next.js/blob/canary/test/integration/amphtml-custom-optimizer/next.config.js

If this config is wrong, we need to fix the test code in zeit/next.js .

**Comment by sebastianbenz** [comment]
I'd suggest removing ` ampUrlPrefix: '/amp'. It's an experimental feature and the behavior has changed how v0.css is resolved (`ampUrlPrefix` needs to be an absolute URL).

**Comment by sebastianbenz** [comment]
Closing this as fixed. 

Sidenote: @yosuke-furukawa not sure if that affects you but the new 2.3.1 release contains a change to the experimental RTV support. RTV URLs must now be enabled via `rtv: true`.
