### ISSUE TITLE
Refactor optimizer

### ISSUE THREAD

**Issue by fstanis** [ampproject/amp-toolbox#75]
# Overview

Refactor the optimizer to achieve two things:

- Separate transformers that result in invalid AMPHTML (e.g. `AmpBoilerplateTransformer`) from the rest.
- Modify the parser to make it more generic, specifically to make it compatible with [posthtml](https://github.com/posthtml/posthtml)

# Background

There are several good practices (e.g. font preconnect) that are beneficial for all AMP pages. The optimizer should offer these transformations that transform "valid AMPHTML into better valid AMPHTML" in addition to offering further optimizations which result in invalid AMPHTML, which comes with a different tradeoff (speed over losing things that come with having valid AMP, such as the cache).

Making the parser compatible with posthtml would make it easy for the optimizer to integrate with an existing large posthtml ecosystem. For example, this allows users to easily combine posthtml transformations with amp-toolbox and allow the optimizer to use existing posthtml integrations, such as express, Koa and Hapi middlewares and integrations with gulp, grunt and webpack.

# Proposal

-   Separate transformers into two groups:
    -   "preamp", for those that make existing valid AMP more efficient while remaining valid
    -   "optimizer", which results in invalid AMPHTML
-   Refactor TreeParser.js:
    -   Replace extensions to `Node` prototype with utility functions.
    -   Either one of these options:
        -   Replace existing parser with [posthtml-parser](https://github.com/posthtml/posthtml-parser) (should be compatible with htmlparser2 interface).
        -   Replace existing parser with an adapter that's compatible with both htmlparser2 and PostHTML AST Format.

Thoughts / comments welcome!

**Comment by sebastianbenz** [comment]
SGTM. Few comments:

* we should provide two different configurations one which optimises AMP and one which performs SSR  (and clearly mark in each transformer whether it breaks validity).
* you need to replace parser and serialiser if you want to replace parse5. 

Can you first find out what's need to make posthtml work with optimiser?

//cc @andreban

**Comment by sebastianbenz** [comment]
Are you still looking into this Filip? Otherwise I'd close this issue...

**Comment by fstanis** [comment]
I'm happy to do this if you feel it's worth investing into a refactor. Otherwise, let's focus on more important issues.

**Comment by sebastianbenz** [comment]
SGTM

**Comment by andreban** [comment]
Closing the issue, as discussed.
