### ISSUE TITLE
Add logging framework with warnings support

### ISSUE THREAD

**Issue by dakkad** [ampproject/amp-toolbox#77]
A number of optimiser modules could make use of logs to warn of potential issue cases for example:

```
<link rel=prefetch href=/img/asset.png />
<link rel=prefetch href=/img/asset.png as=image />

```
In this case it is hard for the duplicate filter to decide which is the correct definition. It is clear that there is a duplication but the optional type `as` attribute validity can't be determined as part of a filter task. In this case offering warnings to the developer to fix issues would be preferable.

Adding logging support across the project to allow consistent messaging.

**Comment by sebastianbenz** [comment]
Fixed in #149
