### ISSUE TITLE
Installation fails with yarn v2

### ISSUE THREAD

**Issue by AleVul** [ampproject/amp-toolbox#813]
Installation fails when trying to install a package that depends on amp-toolbox with yarn v2.

**Error**
`Error: @ampproject/toolbox-optimizer tried to access dom-serializer, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
`

**How to reproduce**

- setup a project with yarn v2
- add nextjs as dep

**Comment by sebastianbenz** [comment]
This has been fixed with the v2.5 release from today. It'll also be in the [next Next.js release](https://github.com/vercel/next.js/pull/13547).
