### ISSUE TITLE
PreloadHeroImage should use imagesrcset attribute not srcset

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-toolbox#823]
I just noticed that the `PreloadHeroImage` transformer is adding a preload `link` with a `srcset` attribute when it should rather be adding `imagesrcset` per https://web.dev/preload-responsive-images/

https://github.com/ampproject/amp-toolbox/blob/4b59cdceddcfe3bb4f39c7e82908561e3576e87a/packages/optimizer/lib/transformers/PreloadHeroImage.js#L62-L81

Also, should not an `imagesizes` attribute be added to the `link` if the `img` has `sizes` attribute?

Lastly, it seems that the Validator hasn't been updated to allow `srcset` (or `imagesrcset`) or `sizes` (or `imagesizes`) on the `link` element:

https://github.com/ampproject/amphtml/blob/1b84e3c0d9899d826c32bdccd99597409ccf0e1d/validator/validator-main.protoascii#L287-L304

Doesn't the transformer currently thus create invalid AMP?

**Comment by westonruter** [comment]
Nevertheless, `imagesrcset` is only supported by Chromium-based browsers per the web.dev article.

**Comment by sebastianbenz** [comment]
Hm. That's tricky. Sounds like not generating a preload statement is the best option if the hero image candidate uses srcset / sizes.
