### ISSUE TITLE
Errors installing @ampproject/toolbox-optimizer@2.4.0 behind proxy

### ISSUE THREAD

**Issue by portenez** [ampproject/amp-toolbox#832]
```bash
npm install --save @ampproject/toolbox-optimizer@2.4.0
```

`node-fetch` does not read the `http_proxy` variables, so there are issues when installing in networks where a proxy is required.

 See `node-fetch` [issue about this](https://github.com/node-fetch/node-fetch/issues/195)

```bash
@ampproject/toolbox-optimizer@2.4.0 postinstall /home/suprauser/workspace/wss_wss_nextjs-demo_PR-39/node_modules/@ampproject/toolbox-optimizer

AMP Optimizer ERROR Could not fetch validator rules { FetchError: request to https://cdn.ampproject.org/v0/validator.json failed, reason: connect ETIMEDOUT 172.217.169.33:443
     at ClientRequest.<anonymous> (/home/suprauser/workspace/node_modules/node-fetch/lib/index.js:1455:11)
     at ClientRequest.emit (events.js:189:13)
     at TLSSocket.socketErrorListener (_http_client.js:392:9)
     at TLSSocket.emit (events.js:189:13)
     at emitErrorNT (internal/streams/destroy.js:82:8)
     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
     at process._tickCallback (internal/process/next_tick.js:63:19)

   message:
    'request to https://cdn.ampproject.org/v0/validator.json failed, reason: connect ETIMEDOUT 172.217.169.33:443',
   type: 'system',
   errno: 'ETIMEDOUT',
   code: 'ETIMEDOUT' }
```

**Comment by sebastianbenz** [comment]
Hm. That's annoying. Not sure what the best way is to fix this. As a workaround you can provide your own fetch implementation:

```
const nodeFetch = require('node-fetch');

const fetch = (url, opts={}) => {
  opts.agent = new HttpsProxyAgent('proxyHost:proxyPort');
  return nodeFetch(url, opts)
}
const optimizer = AmpOptimizer.create({
  fetch,
});
```

Let me know if that works and I'll update the docs.

**Comment by portenez** [comment]
Yes, the problem is that this runs on `postinstall` by the package itself. It is not something that my code is running itself.  The package actually installs, but I don't know the repercussions of this failing.

**Comment by sebastianbenz** [comment]
Got it. The postinstall script failing is no problem. It's just warms up the cache to have a fallback in place in case optimizer is run when offline. We should turn this into a warning instead of an error.

**Comment by portenez** [comment]
@sebastianbenz When I checked there was no issue opened for `nextjs`. I bumped into this problem also because of next. I'm wondering if `nextjs` will need to update the dep in order to get rid of this issue. If that's the case we should open a ticket with `nextjs`

**Comment by sebastianbenz** [comment]
@portenez I've created a PR for Next.js

**Comment by mayank-patel** [comment]
Thanks @portenez & @sebastianbenz you guys rock. I had the same trouble and was going to trace back how to fix this.
