### ISSUE TITLE
Use base64 encoding for sizer SVGs

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-toolbox#844]
As a follow-up to https://github.com/ampproject/amphtml/pull/27518, the sizer SVGs should default to using base64 encoding to be more robust against HTML minification.

Maybe this could be made configurable, so that you can opt to have the raw HTML representation instead, but I think the base64 encoding is the safer default.

**Comment by schlessera** [comment]
@sebastianbenz Any chance of this being accepted if I provide a PR? The produced image tag is:
- more robust against flaky minification implementations
- uses less bytes

<img width="1257" alt="_ 2020-12-03 at 9 11 41 AM p-toolbox-php" src="https://user-images.githubusercontent.com/83631/100988443-073c9a00-3550-11eb-82ed-ed66c7e3896b.png">

**Comment by sebastianbenz** [comment]
Absolutely! Thanks for flagging again, I'm still in the process of slowly catching up with things. PR would be much appreciated!
