### ISSUE TITLE
MinifyHtml Transformer cannot be set to false

### ISSUE THREAD

**Issue by jwinkworth** [ampproject/amp-toolbox#845]
https://github.com/ampproject/amp-toolbox/blob/bf9cdb032c1c35e1c3a11ed288c081ef7631f239/packages/optimizer/lib/transformers/MinifyHtml.js#L41

Seems `opts.minify` will always result to true, regardless of what is passed into config variable.

**Comment by sebastianbenz** [comment]
Fixed in https://github.com/ampproject/amp-toolbox/releases/tag/v2.5.4
