### ISSUE TITLE
Can AmpBoilerplateTransformer be disabled?

### ISSUE THREAD

**Issue by jwinkworth** [ampproject/amp-toolbox#847]
The readme implies that you should be able to enable/disable the boilerplate transformer if you are unable to use it.
https://github.com/ampproject/amp-toolbox/tree/main/packages/optimizer#make-sure-to-enable-amp-boilerplate-removal

> However, under some circumstances it's not possible to remove the boilerplate code...

But I cannot find anywhere that illustrates how to disable it. 

It appears that `config.autoAddBoilerplate` has been depreciated in lieu of `autoAddMandatoryTags`, (which is used by the AddMandatoryTags Transformer) and the readme config section has a broken link.

Asking because I am attempting to run amp-optimizer to auto-populate script tags, but not customize the boilerplate CSS (our AMP pages will not be able to be re-generated weekly as the documentation recommends).

Any guidance would be appreciated.

**Comment by sebastianbenz** [comment]
In that case it's best to manually configure the transformers used. See example [here](https://github.com/ampproject/amp-toolbox/blob/main/packages/optimizer/demo/simple/index.js#L93).

**Comment by jwinkworth** [comment]
Thanks for the speedy reply!
I was expecting that would be the answer, but I just wanted to confirm that I wasn't missing something :)
