### ISSUE TITLE
Optimizer should not remove boilerplate when amp-story is present

### ISSUE THREAD

**Issue by cramforce** [ampproject/amp-toolbox#848]
This is a deviation from Google's optimizer.

Example story:
https://www.seeker.com/stories/why-do-these-robots-swarm-together/

TBH, I'm not 100% certain that URL uses this optimizer. Please let me know if it doesn't.

**Comment by cramforce** [comment]
@shishirm This impacts all NWS docs.

**Comment by rcebulko** [comment]
@cramforce Note: if you use `/ tryassign @ user` (without spaces) it will either assign the issue (if @ user is already a member) or send an invite and then assign the issue after the user accepts the invite.

**Comment by cramforce** [comment]
@rcebulko Cool. In this case, I didn't want to assign, just have an easier time to @-mention the person :)

**Comment by sebastianbenz** [comment]
Fixed in https://github.com/ampproject/amp-toolbox/releases/tag/v2.5.5

**Comment by cramforce** [comment]
Thanks for the super quick fix!

@shishirm Could you confirm with NWS whether they use the optimizer and ask them to upgrade?
