### ISSUE TITLE
Proxy support for amp-optimizer

### ISSUE THREAD

**Issue by todoa2c** [ampproject/amp-toolbox#860]
Using amp-optimizer, fetching data fails if your machine need to connect via proxy, and need to modify source manually.
https://github.com/ampproject/amp-toolbox/tree/main/packages/optimizer#fetch

To use environment variable `https_proxy` is popular and better solution for proxy-user and non-proxy user. 

I created the pull request for this issue.
Please review and merge if no problems found.
https://github.com/ampproject/amp-toolbox/pull/857

Thanks.

**Comment by schlessera** [comment]
This was fixed via #857
