### ISSUE TITLE
Is there Integration with Elementor or Divi?

### ISSUE THREAD

**Issue by RohitR1** [ampproject/amp-toolbox#861]
Is there Integration with Elementor or Divi?

How to use Elementor templates with AMP?

**Comment by sebastianbenz** [comment]
The official [AMP wordpress plugin](https://wordpress.org/plugins/amp/) has AMP Optimizer built in. That should be the right starting point for integration AMP into a wordpress site. Closing as not related to the Node AMP Optimizer.
