### ISSUE TITLE
Npx example in README returns error

### ISSUE THREAD

**Issue by ibrahimcesar** [ampproject/amp-toolbox#868]
**Behavior**
Expected to return the report after run npx command.

**Instruction**
On terminal:

`npx @ampproject/toolbox-linter https://amp.dev/`

Return:

```
linter https://amp.dev/
npx: instalou 118 em 5.511s
comando não existe: toolbox-linter
```

My shell is in Portuguese, but returns that the toolbox-linter command doesn't not exist. Maybe a build problem on latest release?

Tried with our experimental webstory and got same result:

`npx @ampproject/toolbox-linter https://onl.st`

```
linter https://onl.st
npx: instalou 118 em 4.103s
comando não existe: toolbox-linter
```

Node version: **12.18.0**
Npm version: **6.14.4**
System: **Mac OSX 10.15.5**

**Comment by sebastianbenz** [comment]
Thanks, fixed this in the readme. `npx @ampproject/toolbox-cli lint https://amp.dev/` is the correct command.
