### ISSUE TITLE
AMP Optimizer: Why occur the error related to `PreloadHeroImage`? 

### ISSUE THREAD

**Issue by sudokzt** [ampproject/amp-toolbox#888]
I use amp-optimizer with NextJS.

This error "The attribute 'i-amphtml-ssr' may not appear in tag 'amp-img'." is occured.
<img width="577" alt="スクリーンショット 2020-08-11 18 57 37" src="https://user-images.githubusercontent.com/35422367/89980831-9ece6200-dcad-11ea-96f0-d8e3ff4669c7.png">

 'i-amphtml-ssr' is attached in PreloadHeroImage.
https://github.com/ampproject/amp-toolbox/blob/2cc4aa84284e6dde10af75d4b17279e25904b87f/packages/optimizer/lib/transformers/PreloadHeroImage.js#L318

Could you tell me why I am getting this error?

*use versions*
```
next: "9.5.2",
@ampproject/toolbox-core: 2.6.0
@ampproject/toolbox-optimizer: 2.6.0
```

**Comment by sebastianbenz** [comment]
Could you share an example to reproduce? The AMP validator should support
the i-amphtml-ssr attribute. This might either be an unknown corner case or
a caching issue where the validator instance used by Next.js has not been
updated.

**Comment by sudokzt** [comment]
@sebastianbenz 
I'm sorry. I made a mistake with this issue.
I repost https://github.com/ampproject/amp-toolbox/issues/894.
