### ISSUE TITLE
Optimizer tests fail locally

### ISSUE THREAD

**Issue by tharders** [ampproject/amp-toolbox#928]
While the CI pipeline on github seems to run all tests without problems I get lots of failing optimizer tests on my Mac.
```
npm run test:node -- packages/optimizer

Test Suites: 3 failed, 9 passed, 12 total
Tests:       144 failed, 210 passed, 354 total
```

Mac Version: 10.14.6
Node: 10.16.3 and 13.14.0 and 14.12.0

I tried a clean install with different node versions with no success.

**Comment by sebastianbenz** [comment]
Please re-open if still a problem
