### ISSUE TITLE
Update for cross-fetch Dependancy

### ISSUE THREAD

**Issue by TheRealHeyJack** [ampproject/amp-toolbox#934]
cross-fetch was updated due to the node-fetch security vulnerabilities 
`cross-fetch@3.0.5` > `cross-fetch@3.0.6`

**Comment by stubbo** [comment]
Dependancie

**Comment by NoSharp** [comment]
Nice grammar

**Comment by TomDotBat** [comment]
lmao dependancie

**Comment by kachkaev** [comment]
This has been closed by https://github.com/ampproject/amp-toolbox/pull/921, but the release is still pending.

@patrickkettner 🙏

**Comment by damianwadley** [comment]
Is there an ETA on that release?

**Comment by patrickkettner** [comment]
published as alpha4

**Comment by damianwadley** [comment]
Are you sure?

**Comment by kachkaev** [comment]
I see [@ampproject/toolbox-optimizer@2.7.0-alpha.4](https://www.npmjs.com/package/@ampproject/toolbox-optimizer?activeTab=versions). [@ampproject/toolbox-core](https://www.npmjs.com/package/@ampproject/toolbox-core?activeTab=versions) though is still at `2.6.1` (released on 1 October).

**Comment by damianwadley** [comment]
Ah, my bad, I didn't see the tag here so I didn't check if npm had a new version.

**Comment by kachkaev** [comment]
Also note `@ampproject/toolbox-validator-rules@2.5.4` → `cross-fetch@3.0.5` → `node-fetch@2.6.0"`. Other `@ampproject/*` packages might also be affected.

**Comment by sebastianbenz** [comment]
This should be fixed with 2.71.
