### ISSUE TITLE
AMP Optimizer: Elements with the heights or sizes attributes produces invalid AMP when no layout is present.

### ISSUE THREAD

**Issue by Artmann** [ampproject/amp-toolbox#959]
When server-side rendering an document, the optimizer will have to determine the layout to use if none is present. Having a layout is required to be able to [generate the correct styles for the element](https://github.com/ampproject/amp-toolbox/blob/556374697b1e1882dccaa8fa00c5a7c9ed265c74/packages/optimizer/lib/transformers/ApplyLayout.js#L61
).

If the element has a `width`, `height` attribute specified and either a `sizes` or `heights` attribute, the `responsive` layout will be [selected](https://github.com/ampproject/amp-toolbox/blob/556374697b1e1882dccaa8fa00c5a7c9ed265c74/packages/optimizer/lib/ParseLayout.js#L129).

This will add the classes `i-amphtml-layout-responsive` and `i-amp-layout-size-defined` as well as the attribute `i-amp-layout=responsive`. This is does not pass validation when the `layout=responsive` attribute is missing.

For Example, this input

```
<amp-ad
  class=""
  type=taboola
  data-block-on-consent=_till_responded
  width=300
  height=250
  heights="(min-width:616px) 370%, (min-width:472px) 386%, (min-width:375px) 411%, 438%"
  data-publisher=...
  data-mode=thumbnails-a-amp
  data-placement="Mobile Below Article Thumbnails AMP"
  data-article=auto
  data-target_type=mix
>
  ...
</amp-ad>
```

becomes

```
<amp-ad
  class=" i-amphtml-layout-responsive i-amphtml-layout-size-defined"
  type=taboola
  data-block-on-consent=_till_responded
  width=300
  height=250
  data-publisher=diariodebiologia
  data-mode=thumbnails-a-amp
  data-placement="Mobile Below Article Thumbnails AMP"
  data-article=auto
  data-target_type=mix
  i-amphtml-layout=responsive
  id=i-amp-0
>
  <i-amphtml-sizer style="display:block;padding-top:83.3333%;"></i-amphtml-sizer>
</amp-ad>
```

Which doesn't pass AMP Validation. ❌

**Comment by christofferartmannmrf** [comment]
Thanks for the help. ❤️

**Comment by sebastianbenz** [comment]
No problem. Thanks for the detailed bug report!
