### ISSUE TITLE
toolbox-optimizer is not deterministic

### ISSUE THREAD

**Issue by DanielOrtel** [ampproject/amp-toolbox#966]
post install script adds a `.cache` folder with a specific timestamp, which makes the package in the node_modules folder itself non-determenistic. Out of the thousands of packages the app uses, this is the only one which does this, and this package is not one of our direct dependencies, so we can't even remove it. 

This is causing us issues, when trying to create a nix package for one of our app, because every yarn install creates a new package, even if it's not required. 

Is this an absolutely necessary step? Would it be possible to remove the timestamp generation in the post-install script?

**Comment by sebastianbenz** [comment]
I see your point. The timestamp is needed though for cache expiration so I don't really see a way to avoid this. I'm not happy about the post install step either. #973 might be a workaround.

**Comment by sebastianbenz** [comment]
The cache on install has been removed with #1181
